### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by LennyPenny** [TobiEiss/fiGo#8]
Soll das so :thinking: 
https://github.com/TobiEiss/fiGo/blob/96f2dc2792b2f08a771e2cb72803acf6dced73f3/fastconnect/fastconnect.go#L27

**Comment by TobiEiss** [comment]
Ask Beppo 😉

**Comment by LennyPenny** [comment]
![https://i.imgur.com/4gixu9d.jpg](https://i.imgur.com/4gixu9d.jpg)

:kissing_heart: -beppo

**Comment by LennyPenny** [comment]
#9
